version: '3.8'

services:
  user_mngt_api:
    container_name: user_mngt_api_container
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      # Mount the named volume to the 'data' directory inside the container
      - user_mngt_data:/usr/src/app/user_mngt/data 

volumes:
  user_mngt_data: